package io.bootique.cayenne.test.persistence.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _Table1 was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Table1 extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Long> A = new Property<Long>("a");
    public static final Property<Long> B = new Property<Long>("b");

    public void setA(Long a) {
        writeProperty("a", a);
    }
    public Long getA() {
        return (Long)readProperty("a");
    }

    public void setB(Long b) {
        writeProperty("b", b);
    }
    public Long getB() {
        return (Long)readProperty("b");
    }

}
