package io.bootique.cayenne.test.persistence3.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import io.bootique.cayenne.test.persistence3.P3T1;

/**
 * Class _P3T3 was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _P3T3 extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<P3T1> T1 = Property.create("t1", P3T1.class);

    public void setT1(P3T1 t1) {
        setToOneTarget("t1", t1, true);
    }

    public P3T1 getT1() {
        return (P3T1)readProperty("t1");
    }


}
