package io.bootique.cayenne.v41.junit5.persistence3.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.List;

import io.bootique.cayenne.v41.junit5.persistence3.P3T2;
import io.bootique.cayenne.v41.junit5.persistence3.P3T3;
import io.bootique.cayenne.v41.junit5.persistence3.P3T4;
import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _P3T1 was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _P3T1 extends BaseDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<List<P3T2>> T2S = Property.create("t2s", List.class);
    public static final Property<P3T3> T3 = Property.create("t3", P3T3.class);
    public static final Property<List<P3T4>> T4S = Property.create("t4s", List.class);


    protected Object t2s;
    protected Object t3;
    protected Object t4s;

    public void addToT2s(P3T2 obj) {
        addToManyTarget("t2s", obj, true);
    }

    public void removeFromT2s(P3T2 obj) {
        removeToManyTarget("t2s", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<P3T2> getT2s() {
        return (List<P3T2>)readProperty("t2s");
    }

    public void setT3(P3T3 t3) {
        setToOneTarget("t3", t3, true);
    }

    public P3T3 getT3() {
        return (P3T3)readProperty("t3");
    }

    public void addToT4s(P3T4 obj) {
        addToManyTarget("t4s", obj, true);
    }

    public void removeFromT4s(P3T4 obj) {
        removeToManyTarget("t4s", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<P3T4> getT4s() {
        return (List<P3T4>)readProperty("t4s");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "t2s":
                return this.t2s;
            case "t3":
                return this.t3;
            case "t4s":
                return this.t4s;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "t2s":
                this.t2s = val;
                break;
            case "t3":
                this.t3 = val;
                break;
            case "t4s":
                this.t4s = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.t2s);
        out.writeObject(this.t3);
        out.writeObject(this.t4s);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.t2s = in.readObject();
        this.t3 = in.readObject();
        this.t4s = in.readObject();
    }

}
